version: "3"

volumes:
  postgres_volume:

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper_youtube_stats
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.0
    container_name: broker_youtube_stats
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  postgres:
    image: "postgres:15"
    container_name: "postgres_db"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=youtube_project"
    ports:
      - "5555:5432"
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 1m
      timeout: 10s
      retries: 5

  analyzer:
    build: youtube-data-analyzer/
    container_name: "data-analyzer"
    depends_on:
      - broker
    links:
      - postgres:db

  producer:
    build: youtube-data-producer/
    container_name: "producer"
    depends_on:
      - broker
    links:
      - postgres:db